### ISSUE TITLE
PBSV Segmentation Fault

### ISSUE THREAD

**Issue by MikeWLloyd** [PacificBiosciences/pbbioconda#377]
I am running PBSV on a SLURM based compute node, my installation of PBSV is via the most recent docker image (run via singularity). I am using the mm10 genome from iGenomes for alignment and an mm10 simple repeats file from UCSC table browser which is from Tandem Repeats Finder in the PBSV discovery step. I am working with CCS reads. 

I have run several samples with success, but I am encountering a segmentation fault with one sample and I am hoping someone can help me diagnose the issue. Any help on where to look / what to try would be appreciated. 

This is tail of the log file that I have from the most recent attempted run. 

```
...
>|> 20210216 19:55:57.628 -|- DEBUG -|- operator() -|- 0x2aaab4c25700|| -|- Finish polishing deletion  D205678
>|> 20210216 19:55:57.628 -|- DEBUG -|- Polish -|- 0x2aaaaaad0c80|| -|- Filter valid deletion
>|> 20210216 19:55:57.628 -|- DEBUG -|- Polish -|- 0x2aaaaaad0c80|| -|- Deletion sort
>|> 20210216 19:55:57.628 -|- DEBUG -|- Polish -|- 0x2aaaaaad0c80|| -|- Deletion merge
>|> 20210216 19:55:57.628 -|- DEBUG -|- Polish -|- 0x2aaaaaad0c80|| -|- Deletion zygosity
>|> 20210216 19:55:57.629 -|- INFO -|- Polish -|- 0x2aaaaaad0c80|| -|- Deletion polishing finished in 1s 277ms
>|> 20210216 19:55:57.630 -|- INFO -|- Polish -|- 0x2aaaaaad0c80|| -|- Insertion polishing started
>|> 20210216 19:56:02.581 -|- INFO -|- Polish -|- 0x2aaaaaad0c80|| -|- Insertion polishing finished in 4s 951ms
>|> 20210216 19:56:02.616 -|- DEBUG -|- Polish -|- 0x2aaaaaad0c80|| -|- Inversion polishing skipped, no data available
>|> 20210216 19:56:02.616 -|- INFO -|- Polish -|- 0x2aaaaaad0c80|| -|- Duplication polishing started
>|> 20210216 19:56:02.616 -|- INFO -|- Polish -|- 0x2aaaaaad0c80|| -|- Duplication polishing finished in 22us 292ns
>|> 20210216 19:56:02.616 -|- INFO -|- ParseInputFiles -|- 0x2aaaaaad0c80|| -|- Parse until chr5 60000000
>|> 20210216 19:56:02.616 -|- DEBUG -|- ParseStreamUntil -|- 0x2aaaaaad0c80|| -|- Parse input of m64119_201016_230131.fastq.pbmm2.aligned.svsig.gz started
>|> 20210216 19:56:02.713 -|- DEBUG -|- ParseStreamUntil -|- 0x2aaaaaad0c80|| -|- Parse input of m64119_201016_230131.fastq.pbmm2.aligned.svsig.gz in 96ms 319us
>|> 20210216 19:56:02.713 -|- DEBUG -|- ParseUntil -|- 0x2aaaaaad0c80|| -|- Deletion sorting started
>|> 20210216 19:56:02.715 -|- DEBUG -|- ParseUntil -|- 0x2aaaaaad0c80|| -|- Deletion sorting finished in 1ms 878us
>|> 20210216 19:56:02.715 -|- DEBUG -|- ParseUntil -|- 0x2aaaaaad0c80|| -|- Deletion calling started
>|> 20210216 19:56:02.716 -|- DEBUG -|- ParseUntil -|- 0x2aaaaaad0c80|| -|- Deletion calling finished in 1ms 625us
>|> 20210216 19:56:02.716 -|- DEBUG -|- ParseUntil -|- 0x2aaaaaad0c80|| -|- Insertion sorting started
>|> 20210216 19:56:02.723 -|- DEBUG -|- ParseUntil -|- 0x2aaaaaad0c80|| -|- Insertion sorting finished in 7ms 176us
>|> 20210216 19:56:02.723 -|- DEBUG -|- ParseUntil -|- 0x2aaaaaad0c80|| -|- Insertion calling started
>|> 20210216 19:56:02.766 -|- DEBUG -|- ParseUntil -|- 0x2aaaaaad0c80|| -|- Insertion calling finished in 42ms 896us
>|> 20210216 19:56:02.766 -|- DEBUG -|- ParseUntil -|- 0x2aaaaaad0c80|| -|- Inversion sorting started
>|> 20210216 19:56:02.766 -|- DEBUG -|- ParseUntil -|- 0x2aaaaaad0c80|| -|- Inversion sorting finished in 17us 404ns
>|> 20210216 19:56:02.766 -|- DEBUG -|- ParseUntil -|- 0x2aaaaaad0c80|| -|- Inversion calling started
>|> 20210216 19:56:02.769 -|- DEBUG -|- ParseUntil -|- 0x2aaaaaad0c80|| -|- Inversion calling finished in 3ms 147us
>|> 20210216 19:56:02.770 -|- DEBUG -|- ParseUntil -|- 0x2aaaaaad0c80|| -|- Duplications sorting started
>|> 20210216 19:56:02.770 -|- DEBUG -|- ParseUntil -|- 0x2aaaaaad0c80|| -|- Duplications sorting finished in 27us 998ns
>|> 20210216 19:56:02.770 -|- DEBUG -|- ParseUntil -|- 0x2aaaaaad0c80|| -|- Duplications calling started
>|> 20210216 19:56:02.770 -|- DEBUG -|- ParseUntil -|- 0x2aaaaaad0c80|| -|- Duplications calling finished in 26us 562ns
>|> 20210216 19:56:02.779 -|- INFO -|- operator() -|- 0x2aaaaaad0c80|| -|- Insertion consensus started
>|> 20210216 19:56:08.404 -|- INFO -|- operator() -|- 0x2aaaaaad0c80|| -|- Insertion consensus finished in 5s 624ms
>|> 20210216 19:56:08.404 -|- INFO -|- Polish -|- 0x2aaaaaad0c80|| -|- Deletion polishing started
>|> 20210216 19:56:08.404 -|- DEBUG -|- Polish -|- 0x2aaaaaad0c80|| -|- Add deletions for polishing
>|> 20210216 19:56:08.406 -|- DEBUG -|- Polish -|- 0x2aaaaaad0c80|| -|- Start polishing
...
>|> 20210216 19:57:20.884 -|- DEBUG -|- operator() -|- 0x2aaab1208700|| -|- Finish polishing deletion  D205787
-------------------------------------------------------------
EPILOGUE
-------------------------------------------------------------
Job ID: 6474933
Cluster: slurm_cluster
User/Group: root
State: FAILED (exit code 139)
Nodes: 1
Cores per node: 8
CPU Utilized: 10:50:43
CPU Efficiency: 30.44% of 1-11:37:36 core-walltime
Job Wall-clock time: 04:27:12
Memory Utilized: 66.81 GB
Memory Efficiency: 26.72% of 250.00 GB
```

From a different attempt I have the following short log, which I don't think the warning here are important but thought I would include this: 

```
  >|> 20210213 00:33:29.318 -|- WARN -|- Summarize -|- 0x2aaaaaad0c80|| -|- Trying to cluster insertions of different tandem repeats!
...
  >|> 20210213 01:58:14.838 -|- WARN -|- Summarize -|- 0x2aaaaaad0c80|| -|- Trying to cluster insertions of different tandem repeats!
  .command.sh: line 2: 159919 Segmentation fault      pbsv call genome.fa m64119_201016_230131.fastq.pbmm2.aligned.svsig.gz pbsv_calls.vcf
```

**Comment by pb-cdunn** [comment]
You're right; that's not much information to help you debug it. Could you share your data with us somehow? (If secret, use `pb.cdunn` at gmail. Maybe send me a link?) And what version of **pbsv**?

**Comment by MikeWLloyd** [comment]
I took a subset to chr5 and am able to replicate the crash with the data subset. I will send you a link to the data via email.  I am using `pbmm2 1.3.0 (commit 1.3.0)` and `pbsv 2.3.0 (commit v2.3.0)`. As some additional detail, I re-ran the discovery step without the mm10 tadem file from UCSC, and the `call` step completed properly. I suspect something fishy with the interaction of the tandem repeat file and the data. I will include the tandem file in the email.

**Comment by pb-cdunn** [comment]
@MikeWLloyd, I did receive your email. Sorry for the long delay. We are trying to correct the genotyping for a small but significant subset of insertion calls, and that work is time-sensitive. I think we will have time to reproduce your bug this week.

**Comment by pb-cdunn** [comment]
We think your process ran out of memory. On my Mac, it crashes right at 64GB (32GB ["CMPRS"](https://www.lifewire.com/understanding-compressed-memory-os-x-2260327), on my 32GB machine). A more gentle way of exiting would be preferable, but it was crashing in simd code, not in normal C++-style memory allocations.

We are curious _why_ it ran out of memory, but at least it's not a bug (not directly). Re-open if you want to discuss memory issues further. It is something that interests us, but this ticket has been open for 2 months.

**Comment by pb-cdunn** [comment]
Can you tell us where the reads came from? Clr? Hifi? Other?

Typically how long are the alignments?

**Comment by zeeev** [comment]
Hi @MikeWLloyd,

**Comment by pb-cdunn** [comment]
If you generate a new svsig using the latest pbsv-discover, we could use that.

**Comment by MikeWLloyd** [comment]
@zeeev @pb-cdunn will do my best to get the new version up and running and generate the file you need.

**Comment by zeeev** [comment]
Thanks @MikeWLloyd! We appreciate your time.

**Comment by MikeWLloyd** [comment]
To confirm, we are talking about running with: `pbsv_2.6.0--h9ee0642_0`, correct?

**Comment by MikeWLloyd** [comment]
also, just to close the loop on the RAM issue. I fed the tool 250G of RAM during the failed runs. I can try with more, but I have the 2.6.0--h9ee0642_0 running the discovery step now.

**Comment by MikeWLloyd** [comment]
I ran `discovery` with the new version of PBSV (via a singularity container pulled from biocontainers) using the tandem repeat file and genome files used previously. I grepped out chr 5 from the svsig, rebuilt the proper format svsig file and ran the call step. I am seeing the same behavior as before. 

From the log: 
```
…
>|> 20210421 14:12:24.600 -|- INFO -|- ParseInputFiles at ../src/tools/call/CallWorkflow.cpp:402 -|- 0x2aaaaae49f40|| -|- Parse until chr5 60000000
…
>|> 20210421 14:12:30.400 -|- DEBUG -|- operator() at ../src/tools/call/DeletionCaller.cpp:605 -|- 0x2aaaad05b700|| -|- Finish polishing deletion  D5398
>|> 20210421 14:12:59.157 -|- DEBUG -|- operator() at ../src/tools/call/DeletionCaller.cpp:605 -|- 0x2aaaacc59700|| -|- Finish polishing deletion  D5391 

-------------------------------------------------------------
SLURM EPILOGUE
-------------------------------------------------------------
Job ID: 7462299
Cluster: slurm_cluster
User/Group: root/user
State: FAILED (exit code 139)
Nodes: 1
Cores per node: 8
CPU Utilized: 00:14:35
CPU Efficiency: 24.20% of 01:00:16 core-walltime
Job Wall-clock time: 00:07:32
Memory Utilized: 64.75 GB
Memory Efficiency: 25.90% of 250.00 GB
```

I will email the Box link to the updated svsig file.

**Comment by pb-cdunn** [comment]
```
Memory Utilized: 64.75 GB
```
That's interesting. It's failing at the same place as for me, around 64GB, even though your system has 250GB. I don't know how to explain that.

```sh
tabix -c '#' -s 3 -b 4 -e 4 m64119_201016_230131.fastq.pbmm2.chr5.aligned.svsig.gz
[tabix] the compression of 'm64119_201016_230131.fastq.pbmm2.chr5.aligned.svsig.gz' is not BGZF
```
When you modify the svsig, you are using **gzip** instead of **bgzip**. (And if you are manipulating svsig, you have to be careful not to change the order of anything.)

If the full svsig is not too large, I can use that. On the latest **pbsv**, we can use `--region chr5` to skip other processing.

**Comment by armintoepfer** [comment]
The easiest is to share the original data with us via our secure upload https://github.com/PacificBiosciences/pbbioconda#file-sharing

**Comment by MikeWLloyd** [comment]
The full file is 9.8GB. I will have to find a way to get it off my HPC, and I am not sure I can drop a file that size into the web browser uploader and have it go OK. I'll see what I can do.  

I am trying to run with just  `--region chr5`, but it dies with an error asking for an index of `.svsig.gz`. I am also trying to run discover on just `--region chr5` which is throwing a different set of errors I am trying to resolve.

**Comment by pb-cdunn** [comment]
You're right. `9.8GB` is kinda large to share even via the file-sharing website that Armin mentioned.

As you've seen, `--region` requires a tabbix-index, which requires proper sorting, which is tough if you manually modify.

Anyway, I was able to run your latest svsig in 14min. So don't worry about it. We'll try to find a way to skip the memory-intensive processing.

**Comment by MikeWLloyd** [comment]
Well, the file is actually going through the upload process. It is currently at 16%. I sent the file to `bioconda-upload@pacb.com` hopefully it finishes properly.

**Comment by MikeWLloyd** [comment]
'File send successfully'

**Comment by pb-cdunn** [comment]
We have found something we think will reduce memory dramatically for these explosive cases. We are verifying and considering solutions ...

**Comment by acalcino** [comment]
Hello all. Was there a resolution to this problem? I am having the same issue and am very keen to resolve it.

**Comment by zeeev** [comment]
@MikeWLloyd @acalcino, we've found a fix, and we'll be posting an updated version of PBSV soon. Watch for a version bump.

**Comment by pb-cdunn** [comment]
We've released a version with a fix, 2.6.2:

* https://github.com/bioconda/bioconda-recipes/pull/28781

**Comment by james-guevara** [comment]
Hi all,

I am getting a similar problem with the latest version of pbsv (2.6.2). When I run pbsv discover (using SLURM) on a sample (processed with ccs --all and aligned with minimap2), I get out of memory errors. I've allocated up to 512GB of memory for this job, but I get the same error regardless. The input BAM file is 50 GB. 

Here are the final lines of the log error file (using --log-level DEBUG):

```
>|> 20211029 00:24:19.673 -|- INFO -|- ParseRecords at ../src/tools/discover/DiscoverWorkflow.cpp:578 -|- 0x15555552fc00|| -|- Processed records: 690000
>|> 20211029 00:24:30.355 -|- INFO -|- ParseRecords at ../src/tools/discover/DiscoverWorkflow.cpp:578 -|- 0x15555552fc00|| -|- Processed records: 700000
>|> 20211029 00:24:41.370 -|- INFO -|- ParseRecords at ../src/tools/discover/DiscoverWorkflow.cpp:578 -|- 0x15555552fc00|| -|- Processed records: 710000
>|> 20211029 00:24:52.575 -|- INFO -|- ParseRecords at ../src/tools/discover/DiscoverWorkflow.cpp:578 -|- 0x15555552fc00|| -|- Processed records: 720000
>|> 20211029 00:25:04.043 -|- INFO -|- ParseRecords at ../src/tools/discover/DiscoverWorkflow.cpp:578 -|- 0x15555552fc00|| -|- Processed records: 730000
>|> 20211029 00:25:15.321 -|- INFO -|- ParseRecords at ../src/tools/discover/DiscoverWorkflow.cpp:578 -|- 0x15555552fc00|| -|- Processed records: 740000
>|> 20211029 00:25:38.634 -|- INFO -|- ParseRecords at ../src/tools/discover/DiscoverWorkflow.cpp:578 -|- 0x15555552fc00|| -|- Processed records: 750000
>|> 20211029 00:25:49.381 -|- INFO -|- ParseRecords at ../src/tools/discover/DiscoverWorkflow.cpp:578 -|- 0x15555552fc00|| -|- Processed records: 760000
>|> 20211029 00:26:05.544 -|- INFO -|- ParseRecords at ../src/tools/discover/DiscoverWorkflow.cpp:578 -|- 0x15555552fc00|| -|- Processed records: 770000
>|> 20211029 00:26:19.112 -|- INFO -|- ParseRecords at ../src/tools/discover/DiscoverWorkflow.cpp:578 -|- 0x15555552fc00|| -|- Processed records: 780000
>|> 20211029 00:26:31.298 -|- INFO -|- ParseRecords at ../src/tools/discover/DiscoverWorkflow.cpp:578 -|- 0x15555552fc00|| -|- Processed records: 790000
>|> 20211029 00:26:43.977 -|- INFO -|- ParseRecords at ../src/tools/discover/DiscoverWorkflow.cpp:578 -|- 0x15555552fc00|| -|- Processed records: 800000
>|> 20211029 00:27:11.406 -|- INFO -|- ParseRecords at ../src/tools/discover/DiscoverWorkflow.cpp:578 -|- 0x15555552fc00|| -|- Processed records: 810000
>|> 20211029 00:27:37.384 -|- INFO -|- ParseRecords at ../src/tools/discover/DiscoverWorkflow.cpp:578 -|- 0x15555552fc00|| -|- Processed records: 820000
slurmstepd: error: Detected 2 oom-kill event(s) in step 6736835.batch cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.

```

**Comment by zeeev** [comment]
hi @james-guevara can you provide a small reproducible example?

**Comment by james-guevara** [comment]
Hi zeeev, thanks for the response. I ended up splitting by chromosome and running pbsv discover on each chromosome. However, I still get an out-of-memory error on chromosome 2. The chromosome 2 bam file is 12GB and I'm using 120 CPUs (which should allocate 240GB of memory for the job).

Here is the command I use in this case of chr2:

`pbsv discover --sample REACH000236_PB_IGM_CCS_ALL --log-level DEBUG --tandem-repeats human_GRCh38_no_alt_analysis_set.trf.bed --region $CHROM $BAM out_pbsv_discover_chr2/m64278e_210903_184900.ccs.all.mm2.$CHROM.svsig.gz`


Should I share the input bam file with you somehow?

Also, the debug log file ended up being 32GB... I can try to share that as well if necessary.

**Comment by maxineliu** [comment]
I face the same issues and . I used pbmm2 --1.3.0 to generate the aligned bam. My data is super huge. The original bam file is 238GB and then the aligned sorted bam file is 1T. So when I did the pbsv discover (2.8.0) (I also run it on cluster), I requested 24 cups and 48GB memory for the discover job. Finally it failed because of out-of-memory. I guess is more than 1T memory needed for this case?
